cuocthianh/Source/webportalcuocthianh/CameraShop/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ActionServices;
using CoreData;
using Helper;
namespace CameraShop.Controllers
{
    public class CommentController : BaseController
    {

        public CommentController(ICommentActionService Comment) : base(Comment) { }
     //   public static List<Comment> ListComment;
        //
        // GET: /Comment/

        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// View
        /// </summary>
        /// <param name="id"></param>
        /// <param name="type"></param>
        /// <returns></returns>
        public ActionResult _CommentBox(int id, int type)
        {
            if(type==1)
            {
                return PartialView(); //comment picture
            }
            else
            {
                return PartialView(); //comment article
            }
        }


        /// <summary>
        /// Return json object
        /// </summary>
        /// <param name="id"></param>
        /// <param name="type"></param>
        /// <returns></returns>
        public ActionResult CommentBoxJson(int id, int type)
        {
            if (type == 1)
            {
                // return Json(data, JsonRequestBehavior.AllowGet);
                return PartialView(); //comment picture
            }
            else
            {
                // return Json(data, JsonRequestBehavior.AllowGet);
                return PartialView(); //comment article
            }
        }

        /// <summary>
        /// Action
        /// </summary>
        /// <param name="Model"></param>
        /// <returns></returns>
        public ActionResult CommentBox(Comment Model)
        {
            //code insert here
           // return Json(data, JsonRequestBehavior.AllowGet);
            return View();
        }

        public ActionResult _ListComment(int articleid = 0)
        {
           // GetComment(articleid);
            //List<Comment> ListComment = GetComment().Where(x => x.ArticleID == articleid).ToList();
            List<Comment> ListComment = GetComment(articleid);
            return PartialView(ListComment);
        }

        public List<Comment> GetComment(int examid)
        {
            List<Comment> ListComment = new List<Comment>();
            //if (Session["SSComment"] == null)
            //{
            //   Session["SSComment"] = CommentService.GetListByLINQ(c => c.CommentType == 1 && c.ReferenceID == examid);
            //   ListComment = (List<Comment>)Session["SSComment"];
              
            //}
            ListComment = CommentService.GetListByLINQ(x => x.CommentType == 1 && x.ReferenceID == examid).ToList();
            return ListComment;
        }

        public ActionResult _AddComment(int parentid = 0, int articleid = 0, string content = "", string name = "")
        {

            Comment c = new Comment();
            c.ReferenceID = articleid;
            c.ParentID = parentid;
            if (Session["Username"] != null)
            {
                c.Name = Session["Username"].ToString();
            }
            else
            {
                c.Name = name;
            }
            c.CommentContent = content;
            c.PostDate = DateTime.Now;
            // c.UserID = 
            //var ListComment = (List<Comment>)Session["SSComment"];
            //ListComment.Add(c);
            CommentService.Save(c);
            //Session["SSComment"] = ListComment;
            return PartialView(c);
        }
    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Controllers/ExamineeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoreData;
using ActionServices;

namespace CameraShop.Controllers
{
    public class ExamineeController : BaseController
    {
        public ExamineeController(IExamineeActionService _examinee)
            : base(_examinee)
        { }
        //
        // GET: /Examinee/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _ListExaminee() {
            var data = ExamineeService.GetList();
            if (data == null)
                data = new List<Examinee>();
            return PartialView(data);
        }

        public ActionResult Detail(string id="0", string username="") {
            var data = ExamineeService.GetByID(int.Parse(id));
            data.ViewCount += 1;
            ExamineeService.Save(data);
            return View(data);
        }
        [ValidateInput(false)]
        public ActionResult UpdateDescription(string content)
        {
            var examinee = ExamineeService.GetOneByLINQ(c=>c.UserID.Equals(Helper.SessionManagement.GetSessionReturnInt("UserID")));
            if(examinee==null)
                return Content("Fail");
            var data = ExamineeService.GetByID(examinee.ID);
            data.Description = content;

            var c1 = ExamineeService.Save(data);
            if (c1 > 0)
            {
                return Content("OK");
            }
            else
            {
                return Content("Fail");
            }
        }
    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Controllers/PictureExamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoreData;
using ActionServices;
using Helper;
using System.IO;

namespace CameraShop.Controllers
{
    public class PictureExamController : BaseController
    {
        //xu ly up anh/ hien thi anh 
        public PictureExamController(IPictureExamActionService pictureexaminee, IExamineeActionService ex) : 
            base(pictureexaminee, ex) { }

        //
        // GET: /PictureExam/



        public ActionResult Index()
        {
            return View();
        }



        #region Hinh anh
        /// <summary>
        /// Get detail by UserID
        /// </summary>
        /// <returns></returns>
        public ActionResult Detail(int userid=0) {
            var data = PictureExamineeService;
            return View(data);
        }

        /// <summary>
        /// Khung giới thiệu album ảnh
        /// </summary>
        /// <param name="examineeid"></param>
        /// <returns></returns>
        public ActionResult _IntroducePictureExamProfile()
        {
            var users = SessionManagement.GetSessionReturnInt("UserID");
            var data = ExamineeService.GetOneByLINQ(c=>c.UserID.Equals(users));
            return PartialView(data);
        }

        //Picture Exam
        //action
        public ActionResult PictureExam(PictureExam _model)
        {
            return View();
        }

        //Picture Exam
        //view
        public ActionResult _PictureExam()
        {
            var userid = Convert.ToInt32(Session["UserID"]);
            var data = PictureExamineeService.GetListByUserID(userid);
            if (data != null && data.Count >= 1)
                Session["uploadover"] = "OK"; //chi dc  up một tấm ảnh
            else
            {
                Session["uploadover"] = null;
            }
            return PartialView();
        }
        /// <summary>
        /// hien thi danh sach hinh anh tron profile
        /// </summary>
        /// <param name="userid"></param>
        /// <returns></returns>
        public ActionResult _ListPictureExamProfile()
        {
            var userid =  Convert.ToInt32(Session["UserID"]);
            var data = PictureExamineeService.GetListByUserID(userid);
          //  if (data != null && data.Count > 1)
              //  Session["uploadover"] = "OK"; //chi dc  up một tấm ảnh
            return PartialView(data);
        }

        //Picture Exam
        //view
        public ActionResult _ListPictureExam(int userid=0)
        {
            if (userid == 0)
            {
                userid = Convert.ToInt32(Session["UserID"]);
            }
             var data = PictureExamineeService.GetListByUserID(userid);
             return PartialView(data);
        }

        public ActionResult Delete(int id = 0) {
            var picex = PictureExamineeService.GetByID(id);
            var picname = picex.Image;
            if (PictureExamineeService.Delete(picex)==true){
                string fullPath = Request.MapPath("~/Media/PictureExam/" + picex.Image);
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
            }
            return PartialView("_ListPictureExamProfile");
        }

        #region upload control

        //uoload control
        public ActionResult UploadPicture(PictureExam model, HttpPostedFileBase file)
        {
            var userid = Convert.ToInt32(Session["UserID"]);
            var data = PictureExamineeService.GetListByUserID(userid);
            if (data != null && data.Count >= 1)
                return Json("Bạn chỉ có thể upload một ảnh duy nhất", JsonRequestBehavior.AllowGet);
            model.Image = PathUpload;
            if (model.Image != "")
            {
                string path = Server.MapPath("~/Media/PictureExam/" + Path.GetFileNameWithoutExtension(model.Image) + "thum" + Path.GetExtension(model.Image));
                model.ThumnailImg = Helper.ImageHelper.ScropImage(Server.MapPath("~/Media/PictureExam/" + model.Image), path, 200, 250);
            }
            else
            { model.ThumnailImg = ""; }

            model.ExamineeID = int.Parse(Session["ExamineeID"].ToString());
            var check = PictureExamineeService.GetOneByLINQ(c => c.ExamineeID == (model.ExamineeID));
            if (check != null)
                model.ID = check.ID;
            var id = this.PictureExamineeService.Save(model);
            PathUpload = "";
            return Json(id, JsonRequestBehavior.AllowGet);
        }
                    

        #endregion


        #endregion

    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Examinee/Detail.cshtml
@{
    ViewBag.Title = "Album dự thi cuộc thi ảnh JBart - "+@Model.UserNameExt;
    Layout = "~/Views/Shared/_Layout.cshtml";

}
    @{
  
             
                 var link = "http://cuocthijba.com/album/" + Model.UserNameExt.Replace(" ", "-") + "-p"+Model.ID+".html";
   } 
@section HeadResource{

<!-- for Facebook -->          
<meta property="og:title" content="Học viện đào tạo thẩm mỹ JBart" />
<meta property="og:type" content="article" />
<meta property="og:image" content="http://cuocthijba.com/Media/PictureExam/@Model.ThumnailimgExt" />
<meta property="og:url" content="@link" />
<meta property="og:description" content="Album dự thi cuộc thi ảnh JBart - @Model.UserNameExt" />

<!-- for google-->
    <meta itemprop="name" content="Học viện đào tạo thẩm mỹ JBart" />
    <meta itemprop="description" content="Album dự thi cuộc thi ảnh JBart - @Model.UserNameExt" />
    <meta itemprop="url" content="@link" />
 @*    <meta property="og:image"  content="http://cuocthijba.com/Media/PictureExam/@Model.Image" />*@
     <meta itemprop="image" content="http://cuocthijba.com/Media/PictureExam/@Model.ThumnailimgExt" />



  
}
@using CoreData
@model Examinee
  
@if (Model != null)
{
    <input type ="hidden" value="@Model.ID" name="txtid" id="txtid" />
    <div class="container clearfix">
        <div class="postWrap">
            <div class="post-292 post type-post status-publish format-standard has-post-thumbnail hentry category-commercial">
                <div class="contentbox">
                    <div class="topbar">
                        <p class="space border-color-5">
                          Hình ảnh</p>
                    </div>
                    <p class="featured-image">
                        <img src="/Media/PictureExam/@Model.Image" alt="">
                    </p>
                    <div class="textbox clearfix">
                      @Html.Raw(Model.Description)
                    </div>
                    @*<p class="categories">
                    Categories: &nbsp; <a href="http://pinthis-rtl.pixelbeautify.com/category/commercial/"
                        title="شاهد جميع المقالات في Commercial" rel="category tag">Commercial</a></p>*@
                    @*<div class="metabar clearfix">
                        <h4 class="title-5">
                            Bình luận</h4>
                    </div>*@
                    <!-- <div class="comment-respond-wrapper "> -->
                    @*<div>
                      <center>
                    <div class="fb-comments" data-href="@Model.Link" data-width="100%" data-numposts="5" data-colorscheme="dark"></div>
                   </center>
                   </div>*@
                    @*<div class="comments" id="mainComment">
                        @Html.Action("_ListComment", "Comment", new { @articleid = Model.ID })
                    </div>
                    <div id="respond" class="comment-respond">
                        <p class="comment-form-url">
                            <input id="txtname" name="txtname" placeholder="Name " type="text" value></p>
                        <p class="comment-form-comment">
                            <textarea id="commentcontent" name="commentcontent" placeholder="Comment " aria-required="true"></textarea></p>
                        <p class="form-submit">
                            <input name="submitcomment" class="button button-color-1" type="submit" id="submitcomment"
                                value="Comment">
                        </p>
                    </div>*@
                    <!-- #respond -->
                    <!-- </div> -->
                </div>
                <div style="width:100%; height:2px; background:#999999; margin-top:10px; margin-bottom:10px"></div>
                <div style="font-size:large">Bình luận</div>
                <div>
                     <center>
                        <div class="fb-comments" data-href="@link" data-width="100%" data-numposts="15" data-colorscheme="dark"></div>
                       </center>
                </div>
            </div>
        </div>
        <aside class="sidebar">
            <div class="contentbox">
                <h4 class="title-1 border-color-2">
                    Album</h4>
                <div class="widgetwrapper">
                    <ul class="recentposts clearfix">
                        @Html.Action("_ListPictureExam", "PictureExam", new { @userid = @Model.UserID })
                    </ul>
                </div>
            </div>
        </aside>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $(".recentposts").find("li").click(function (e) {
            e.preventDefault() ? e.preventDefault() : e.returnValue;
            $(".featured-image").find("img").attr("src", $(this).find("img").attr("src"))
        });
    });

  

</script>

<div id="fb-root"></div>
<script>    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&appId=331902120290983&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);
    } (document, 'script', 'facebook-jssdk'));</script>

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Examinee/_ListExaminee.cshtml
@using CoreData
@model List<Examinee>
@{

 }
@foreach (var item in Model)
{
    string title = "Ảnh dự thi cuộc thi ảnh jba - Jbart Academy";
    var link = "http://cuocthijba.com/" + "album/"+item.UserNameExt.Replace(" ","-")+"-p"+item.ID+".html";
    <article class="pinbox">
        <div class="post-122 post type-post status-publish format-standard has-post-thumbnail sticky hentry category-landscapes tag-dummy tag-industry tag-ipsum tag-lorem tag-printing tag-simply tag-text tag-typesetting">
            <div class="top-bar">
                <ul class="social-media-icons clearfix">
                    <li><a href="https://www.facebook.com/sharer/sharer.php?u=@link&t=@title"
                        class="border-color-3 icon-facebook tooltip" title="Share on Facebook" target="_blank">
                        Facebook</a></li>
                    <li><a href="https://plus.google.com/share?url=@link"
                        class="border-color-1 icon-gplus tooltip" title="Share on Google+" target="_blank">
                        Google+</a></li>
                    <li><a href="https://twitter.com/share?url=@link"
                        class="border-color-4 icon-twitter tooltip" title="Share on Twitter" target="_blank">
                        Twitter</a></li>
                </ul>
            </div>
            <div class="preview">
                <p class="thumb">
                    <a href="@Url.Action("Detail", "Examinee", new { id = "" + @item.ID + "", username = @item.UserNameExt.Replace(" ", "-") })" title="">
                       @if(!String.IsNullOrEmpty(item.Image))
                       {
                           <img src="/Media/PictureExam/@item.Image" width="236" height="208" alt="" />
                       }
                       else
                       {
                           <img src="#" width="236" height="208" alt="" />
                       }
                    </a>
                </p>
            </div>
            <div class="title">
                <h2 class="title-2">
                    <a href="@Url.Action("Detail", "Examinee", new {  id = ""+@item.ID+"", username = @item.UserNameExt.Replace(" ","-") })">Số báo danh: @item.Code - @item.UserNameExt</a>
                    </h2>
            </div>
            <div class="excerpt">
                
                   @* @item.Description*@
                   Album dự thi
                
            </div>
            <div class="meta-data">
                <ul class="clearfix">
                    <li class="border-color-1 tooltip " title="Lượt xem"><span class="icon-total-comments">
                        @item.ViewCount</span> </li>
                    <li class="border-color-2 tooltip " title="Ngày đăng ký"><span class="icon-post-date">@item.DayOfBirth.ToString("dd.MM.yyyy")</span>
                    </li>
                </ul>
            </div>
        </div>
    </article>
}