cuocthianh/Source/webportalcuocthianh/CameraShop/Areas/Administrator/Controllers/ManufacturerManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoreData;
using ActionServices;
using Helper;

namespace CameraShop.Areas.Administrator.Controllers
{
    public class ManufacturerManagementController : BaseController
    {
        //
        // GET: /Administrator/ManufacturerManagement/

        public ManufacturerManagementController(IManufacturerActionService manufacturer, IConfigurationActionService config)
            : base(manufacturer, config)
        {
            try
            {
                Permission = ListPermission.FirstOrDefault(c => c.Module.Equals(Helper.ValueDefine.MANUFACTURER)).Role;
            }
            catch { }
        }

        #region Main 

        public ActionResult Index()
        {
            return SetUpSecurity();
        }

        public ActionResult _ShowAll()
        {
            var data = ManufacturerService.GetList();
            return PartialView(data);
        }

        #endregion

        #region CRUD
        /// <summary>
        /// view
        /// </summary>
        /// <returns></returns>
        public ActionResult AddOrUpdate(int id = 0)
        {
            return CanUpdate((int)id);
        }

        public ActionResult _AddOrUpdate(int id)
        {
            var data = ManufacturerService.GetByID(id);
            return PartialView(data);
        }

        /// <summary>
        /// Action
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddOrUpdate(Manufacturer model, HttpPostedFileBase file)
        {
            var exist = this.ManufacturerService.GetOneByLINQ(c => c.Name.Equals(model.Name));
            if (exist != null && model.ID == 0)
            {
                return Content("exist");
            }
            model.Image = PathUpload;
            var id = this.ManufacturerService.Save(model);
            PathUpload = "";
            var data = this.ManufacturerService.GetByID(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Delete(int id)
        {
            this.ManufacturerService.Delete(this.ManufacturerService.GetByID(id));
            return RedirectToAction("Index", "CategoryManagement");
        }
        #endregion

    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Areas/Administrator/Views/ManufacturerManagement/AddOrUpdate.cshtml
@{
    ViewBag.Title = "Thêm hoặc chỉnh sửa";
}
@using Helper

<script src="@Url.ContentArea("~/Content/javascript/manufacturer.js")" type="text/javascript"></script>
@Html.Action("_AddOrUpdate", "ManufacturerManagement", new { id = Model })

<script type="text/javascript">
    ///Document Ready jQuery
    $(document).ready(function () {

        $('#fileupload').fileupload({
            dataType: 'json',
            url: '/Administrator/ManufacturerManagement/UploadFiles?dir=Manufacturer',
            autoUpload: true,
            done: function (e, data) {
                $('#image').html('<img width=\"70px\" height=\"70px\" src="/Media/Manufacturer/' + data.result.name + '" />');

            }
        }).on('fileuploadprogressall', function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.progress .progress-bar').css('width', progress + '%');
        });

    });
</script>

cuocthianh/Source/webportalcuocthianh/CameraShop/Areas/Administrator/Views/ManufacturerManagement/Index.cshtml
@{
    ViewBag.Title = "Nhà sản xuất";
}
<div class="head">
    <div class="isw-grid">
    </div>
    <h1>
        Danh sách nhà sản xuất</h1>
    <ul class="buttons">
        <li><a href="#" class="isw-settings"></a>
            <ul class="dd-list" style="display: none;">
             @if (CameraShop.BaseController.Permission.Contains("C"))
             {
                 
                <li><a href="@Url.Action("AddOrUpdate", "ManufacturerManagement")"><span class="isw-plus"></span>Thêm
                    nhà sản xuất</a></li>
                 
             }
            </ul>
        </li>
    </ul>
    <div class="clear">
    </div>
</div>
<div class="block-fluid table-sorting">
    <div class="row-fluid list">
     @if (CameraShop.BaseController.Permission.Contains("R"))
     {
        @Html.Action("_ShowAll", "ManufacturerManagement")
     }
     else
     {
         <span>Bạn không có quyền truy cập trang này</span> 
     }
    </div>
</div>



cuocthianh/Source/webportalcuocthianh/CameraShop/Areas/Administrator/Views/ManufacturerManagement/_AddOrUpdate.cshtml
@model CoreData.Manufacturer
@{ 
    ViewBag.Title = "Thêm nhà sản xuất";
}
<div class="row-fluid">
    <div class="span12">
        <div class="head">
            <div class="isw-documents">
            </div>
            <h1>
                Thêm nhà sản xuất</h1>
            <div class="clear">
            </div>
        </div>
        <div class="block-fluid tabs">
            <ul>
                <li><a href="#tabs-1">Nội dung trang</a></li>
                <li><a href="#tabs-2">Quản lý SEO</a></li>
            </ul>
            @using (Ajax.BeginForm("AddOrUpdate", "ManufacturerManagement", new AjaxOptions { OnSuccess = "Success", HttpMethod = "Post" }, new { enctype = "multipart/form-data", @id = "validation" }))
            {
                <div class="warning-area">
                </div>
                <div id="tabs-1">
                    @Html.HiddenFor(x => x.ID)
                    <div class="row-form">
                        <div class="span2">
                            Tên nhà sản xuất:</div>
                        <div class="span9">
                            @Html.TextBoxFor(x => x.Name, new { @class = "validate[required]" })</div>
                        <div class="clear">
                        </div>
                    </div>
                    <div class="row-form">
                        <div class="span2">
                            Hình ảnh :</div>
                        <div class="span8">
                            <input id="fileupload" type="file" name="file" />
                            @if (Model != null && Model.Image != null && Model.Image != "")
                        {
                                <div id="image">
                                   <img src="@Url.Content("~/Media/Manufacturer/" + Model.Image)" width="70px" height="70px" alt="@Model.Image" />
                                </div>
                          
                        } else
                            {
                                <div id="image"> 
                                 </div>
                            }
                        </div>
                        <div class="clear">
                        </div>
                    </div>
                    <div class="row-form">
                        <div class="span2">
                            Mô tả</div>
                        <div class="span9">
                            @Html.TextAreaFor(x => x.Note, new { @cols = "10", @rows = "10" })</div>
                        <div class="clear">
                        </div>
                    </div>
                    <div class="row-form">
                        <div class="span2">
                            Kích hoạt :</div>
                        <div class="span9">
                            @Html.CheckBoxFor(x => x.Active)</div>
                        <div class="clear">
                        </div>
                    </div>
                </div>
                <div id="tabs-2">
                    <div class="row-form">
                        <div class="span2">
                            Link :</div>
                        <div class="span9">
                            @Html.TextBoxFor(x => x.Link)</div>
                        <div class="clear">
                        </div>
                    </div>
                    <div class="row-form">
                        <div class="span2">
                            Meta Title :</div>
                        <div class="span9">
                            @Html.TextAreaFor(x => x.MetaTitle)</div>
                        <div class="clear">
                        </div>
                    </div>
                    <div class="row-form">
                        <div class="span2">
                            Meta Keyword :</div>
                        <div class="span9">
                            @Html.TextAreaFor(x => x.MetaKeyword)</div>
                        <div class="clear">
                        </div>
                    </div>
                    <div class="row-form">
                        <div class="span2">
                            Meta Description :</div>
                        <div class="span9">
                            @Html.TextAreaFor(x => x.MetaDescription)</div>
                        <div class="clear">
                        </div>
                    </div>
                </div>
               
                 if (CameraShop.BaseController.Permission.Contains("U") || CameraShop.BaseController.Permission.Contains("C"))
                 {
                <div class="row-form">
                    <div class="span2">
                    </div>
                    <div class="span9">
                        <input type="submit" class="btn btn-info span3" value="Cập nhật" /></div>
                    <div class="clear">
                    </div>
                </div>
                 }
            }
        </div>
    </div>
</div>

cuocthianh/Source/webportalcuocthianh/CameraShop/Areas/Administrator/Views/ManufacturerManagement/_ShowAll.cshtml
@using CoreData
@model IEnumerable<Manufacturer>
@if (Model!=null&&Model.Count() > 0)
{
    int i = 0;
    <table cellpadding="0" cellspacing="0" width="100%" class="table" id="tSortable">
        <thead>
            <tr>
                <th width="20px">STT
                </th>
                <th>Tên nhà sản xuất
                </th>
                <th width="70px">Hình ảnh</th>
                <th>Mô tả
                </th>
                <th width="60px">Trạng thái
                </th>
                <th width="60px">Chức năng
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                i++;
                <tr>
                    <td>
                        @i
                    </td>
                    <td>
                        <span class="SpanId" style="display: none;">@item.ID</span>
                        <span class="SpanName" style="display: none;">@item.Name</span>
                        @item.Name
                    </td>
                    <td>
                      <img src="@Url.Content("~/Media/Manufacturer/" + item.Image)" width="70px" height="70px" alt="@item.Name" /></td>

                    <td>
                        @item.Note
                    </td>
                    <td>
                        @Html.CheckBoxFor(x => item.Active, new { @disabled = "disabled" })
                    </td>
                    <td>
                     @if (CameraShop.BaseController.Permission.Contains("U"))
                     {
                        <a title="Sửa" href="@Url.Action("AddOrUpdate", "ManufacturerManagement", new { id = item.ID })" class="icon-pencil"></a>
                     }
                      @if (CameraShop.BaseController.Permission.Contains("D"))
                      {
                        <a title="Xóa" href="@Url.Action("Delete", "ManufacturerManagement", new { id = item.ID })" class="icon-trash" onclick="return confirm('Có chắc bạn muốn xóa ?');"></a>
                      }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h2 class="error-text">Không tìm thấy dữ liệu.
    </h2>
}