cuocthianh/Source/webportalcuocthianh/CameraShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoreData;
using ActionServices;

namespace CameraShop.Controllers
{
    public class CategoryController : BaseController
    {
        //
        // GET: /Category/
        public CategoryController(ICategoryActionService _category, IConfigurationActionService _config)
            : base(_category, _config)
        { }

        /// <summary>
        /// Menu danh mục sản phẩm
        /// </summary>
        /// <returns></returns>
        public ActionResult _NavigationCategory()
        {
            var model = CategoryService.GetListByLINQ(x => x.Active == true);
            return PartialView(model);
        }
        /// <summary>
        /// Menu danh mục sản phẩm trong trang Category
        /// </summary>
        /// <param name="CatId"></param>
        /// <returns></returns>
        public ActionResult _GetChildCategory(int CatId) {
            var model = CategoryService.GetListByLINQ(x=> x.Active== true && x.ParentID==CatId);
            return PartialView(model);
        }
    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoreData;
using ActionServices;

namespace CameraShop.Controllers
{
    public class SearchController : BaseController
    {
        //
        // GET: /Search/

        public SearchController(ISearchActionService search, ICategoryActionService category):base(search, category){}

        public ActionResult Index(string value = "", int catid = 0, int page = 1, int pageSize = 10)
        {
            var data = SearchService.SearchAll(value, catid).ToList();
            foreach (var item in data)
            {
                item.PageExt = page;
                item.PageSizeExt = pageSize;
                item.TotalPageExt = (int)Math.Ceiling((float)data.Count / (float)item.PageSizeExt);
                item.CountItemExt = data.Count();
                item.CatID = catid;
            }
            data = data.OrderByDescending(x => x.Name).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            ViewBag.TitleName = value;
            return View(data);
        }
        /// <summary>
        /// Search Post back
        /// </summary>
        /// <param name="model">Search Model</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(Search model, int page = 1, int pageSize = 10)
        {
            var data = SearchService.SearchAll(model.Name, model.CatID).ToList();
            foreach (var item in data) {
                item.PageExt = page;
                item.PageSizeExt = pageSize;
                item.TotalPageExt = (int)Math.Ceiling((float)data.Count / (float)item.PageSizeExt);
                item.CountItemExt = data.Count();
                item.CatID = model.CatID;
            }
            data = data.OrderByDescending(x => x.Name).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            ViewBag.TitleName = model.Name;
            return View(data);
        }

        /// <summary>
        /// Search Input Control on Header
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public ActionResult _SearchInputControl() {
            var data = SearchService.GetSelectListCategory();
            Search cat = new Search();
            if (data != null)
            {
                cat.ListCategoryExt = data;
            }
            return PartialView(cat);
        }

        /// <summary>
        /// Search
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public JsonResult SearchAll(string value, int id=0)
        {  
            var model = SearchService.SearchAll(value, id).Take(40).ToList();
            foreach(var item in model){
                if (item.Type == null) {
                    item.Type = "";
                }
            }
            return Json(model ,JsonRequestBehavior.AllowGet);
        }

    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Search/Index.cshtml
@using CoreData
@using Helper
@model IList<Search>
@{
    var TitleName = @ViewBag.TitleName;
    ViewBag.Title = "Tìm kiếm cho từ khóa " + '"' + @TitleName + '"';
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@helper pagerHelper()
    {
        var TitleName = @ViewBag.TitleName;
        int totalPage = Model.FirstOrDefault().TotalPageExt;
        int currentPage = (int)Model.First().PageExt;
        int i = 0;
        var catId = Model.FirstOrDefault().CatID;
    <ul>
        <li class="bullet-first"><a href="@Url.Action("Index", "Search", new { @page = 1, @catid = catId, @value = TitleName })">
            <<</a></li>
        @if (currentPage > 1)
        {
            <li class="bullet-prev"><a href="@Url.Action("Index", "Search", new { @page = currentPage - 1, @catid = catId, @value = TitleName })">
                <</a></li>
        }
        @if (totalPage > 0)
        {
            var startPage = currentPage - 2;
            var endPage = currentPage + 2;
            if (startPage < 1) { startPage = 1; }
            if (endPage > totalPage) { endPage = totalPage; }

            if (currentPage >= 4)
            {
            <li>...</li>
            }
            for (i = startPage; i <= endPage; i++)
            {
                if (currentPage == i)
                {
            <li class="current-page"><a href="@Url.Action("Index", "Search", new { @page = i, @catid = catId, @value = TitleName })">@i</a></li>
                }
                else
                {
            <li><a href="@Url.Action("Index", "Search", new { @page = i, @catid = catId, @value = TitleName })">@i</a></li>
                }
            }
            if (currentPage <= totalPage - 2)
            {
            <li>...</li>
            }
        }
        @if (currentPage < totalPage)
        {
            <li class="bullet-next"><a href="@Url.Action("Index", "Search", new { @page = currentPage + 1, @catid = catId, @value = TitleName })">
                ></a></li>
        }
        <li class="bullet-last"><a href="@Url.Action("Index", "Search", new { @page = totalPage, @catid = catId, @value = TitleName })">
            >></a></li>
    </ul>
}
@section HeadResource{
    <title>@ViewBag.Title</title>
}
<div class="container fluid">
    <div class="boxcontainer">
        @foreach (var item in Model)
        {
            var Description = item.Description;
            if (item.Description.Length > 170)
            {
                Description = item.Description.Substring(0, 120) + "...";
            }
            <article class="pinbox">
                <div class="post-122 post type-post status-publish format-standard has-post-thumbnail sticky hentry category-landscapes tag-dummy tag-industry tag-ipsum tag-lorem tag-printing tag-simply tag-text tag-typesetting">
                    <div class="preview">
                        <p class="thumb">
                            <a href="@item.Link" title="Donec euismod fermentum">
                                <img src="@item.Image" width="236"
                                            height="208" alt="Donec euismod fermentum">
                            </a>
                        </p>
                    </div>
                    <div class="title">
                        <h2 class="title-2">
                            <a href="@item.Link">@item.Name</a></h2>
                    </div>
                    <div class="excerpt">
                        @Description
                    </div>
                </div>
            </article>
        }
    </div>
    @*<aside class="sidebar">
        @if (Model.Count() > 0)
        {
            <div class="contentbox">
                <h4 class="title-1 border-color-2">
                    أحدث المقالات</h4>
                @Html.Action("_GetChildCategory", "Category", new { @CatId = Model.First().CatID })
            </div>
        }
    </aside>*@
</div>
@section BottomResource{
    <script src="@Url.Content("~/Content/js/search.js")" type="text/javascript"></script>
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Search/_SearchInputControl.cshtml
@using CoreData
@model Search
@using (Html.BeginForm("Index", "Search", FormMethod.Post))
{
    @Html.TextBoxFor(x => x.Name, new { @class = "txt", @value="Search",  @id = "txtNavSearch", @autocomplete = "off" })
    @*<input type="text" name="s" value="Search" />*@
    <input type="submit" value="Search" />
}