cuocthianh/Source/webportalcuocthianh/CameraShop/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoreData;
using ActionServices;

namespace CameraShop.Controllers
{
    //trừ trường hợp bất khả kháng không thể xử lý ở mức service mới được phép xử lý trên controller
    public class ArticleController : BaseController
    {
        //
        // GET: /Article/
        public ArticleController(IArticleActionService _article, IUserActionService _user, IConfigurationActionService _config)
            : base(_article, _user,_config)
        { }

        /// <summary>
        /// View All Article
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(int catid = 0, string username = "", int page = 1, int PageSize = 8)
        {
            try
            {
                var article = ArticleService.GetListByRelationsID(catid, username);
                foreach (var item in article)
                {
                    item.pageExt = page;
                    item.PageSizeExt = PageSize;
                    item.TotalPageExt = (int)Math.Ceiling((float)article.Count / (float)item.PageSizeExt);
                }
                article = article.Skip(PageSize * (page - 1)).Take(PageSize).ToList();
                return View(article);
            }
            catch {
                return View();
            }
        }

        /// <summary>
        /// View Detail Product
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult Detail(long id, string name="")
        {
            var data = ArticleService.GetByID(id);
            if (data == null)
                data = new Article();
            var user = UserService.GetByID(data.UserID);
           if(user!=null)
               data.UserNameExt = user.UserName;
            data.ListSameArticleExt = ArticleService.GetSameListByCateID(data.ID, 5);
            return View(data);
        }
        /// <summary>
        /// PartialView NewArticle on Home Page
        /// </summary>
        /// <returns></returns>
        public ActionResult _NewArticles()
        {
            var article = ArticleService.GetListByLINQ(x=> x.ShowHomePage && x.Active).OrderByDescending(x=>x.UpdateDate).Take(5);
            return PartialView("_NewArticles", article);
        }


        public ActionResult _GetArticleDefault()
        {
            var article = ArticleService.GetList();
            return PartialView(article);
        }

    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Controllers/BannerLogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ActionServices;
using CoreData;
using Helper;
using System.Text.RegularExpressions;
namespace CameraShop.Controllers
{
    public class BannerLogoController : BaseController
    {
        //
        // GET: /BannerLogo/
        public BannerLogoController(IBanner_LogoActionService _banner)
            : base(_banner)
        { }
        /// <summary>
        /// Banner On Main Page
        /// </summary>
        /// <returns></returns>
        public ActionResult _MainSlideShow()
        {
            IList<Banner_Logo> banner = BannerService.GetList();// (x => x.Active == true && x.Type == ValueDefine.BannerLogoType.Banner && x.Position == ValueDefine.BannerLogoPosition.ShideShow).Take(5).ToList();
            return PartialView(banner);
        }

        /// <summary>
        /// SlideShow ben hong SlideShow chinh
        /// </summary>
        /// <returns></returns>
        public ActionResult _SubSlideShow()
        {
            IList<Banner_Logo> banner = BannerService.GetListByLINQ(x => x.Active == true && x.Type == ValueDefine.BannerLogoType.Banner && x.Position == ValueDefine.BannerLogoPosition.RightSlider).Take(3).ToList();
            return PartialView(banner);
        }
        /// <summary>
        /// Show Banner on Column by Position
        /// </summary>
        /// <param name="position"></param>
        /// <returns></returns>
        public ActionResult _ColumnBanner(ValueDefine.BannerLogoPosition position=ValueDefine.BannerLogoPosition.LeftBanner, long CatId=0) {
            IList<Banner_Logo> banner = BannerService.GetListByLINQ(x => x.Active == true && x.Type == ValueDefine.BannerLogoType.Banner && x.Position == position && x.ProductCateID==CatId);
            return PartialView(banner);
        }
    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Controllers/CustomerIdeaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ActionServices;
using CoreData;
using Helper;

namespace CameraShop.Controllers
{
    public class CustomerIdeaController : BaseController
    {
        public CustomerIdeaController(ICustomerIdeaActionService _customeridea, IUserActionService _user)
            : base(_customeridea, _user)
        { }
        //
        // GET: /CustomerIdea/
        /// <summary>
        /// Partial View Of Add Order Detail Comment
        /// </summary>
        /// <param name="_orderid"></param>
        /// <returns></returns>
        public ActionResult _AddOrderDetailComment(int _orderid)
        {
            OrderID = _orderid;
            return PartialView();
        }
        /// <summary>
        /// Action
        /// </summary>
        /// <param name="model"></param>
        /// <param name="file"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult _AddOrderDetailComment(CustomerIdea model, HttpPostedFileBase file)
        {
            try
            {
                model.Attachment = PathUpload;
                model.UserID = Userid;
                model.Type = 1;
                PathUpload = "";
                model.OrderID = OrderID;
                model.ID = 0;
                var _user = UserService.GetByID(Userid);
                model.Email = _user.Email;
                CustomerIdeaService.Save(model);
                return RedirectToAction("Detail", "Order", new { id=OrderID});
            }
            catch {
                return RedirectToAction("Detail", "Order", new { id = OrderID });
            }
        }
        /// <summary>
        /// View
        /// </summary>
        /// <returns></returns>
        public ActionResult _AddContactComment()
        {
            return PartialView();
        }
        /// <summary>
        /// Action
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult _AddContactComment(CustomerIdea model) {
            try {
                model.UserID = Userid;
                model.Type = 2;
                model.ID = 0;
                CustomerIdeaService.Save(model);
                return RedirectToAction("Contact", "Home");
            }
            catch {
                return RedirectToAction("Contact", "Home");
            }
        }
    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Controllers/ExamineeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoreData;
using ActionServices;

namespace CameraShop.Controllers
{
    public class ExamineeController : BaseController
    {
        public ExamineeController(IExamineeActionService _examinee)
            : base(_examinee)
        { }
        //
        // GET: /Examinee/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _ListExaminee() {
            var data = ExamineeService.GetList();
            if (data == null)
                data = new List<Examinee>();
            return PartialView(data);
        }

        public ActionResult Detail(string id="0", string username="") {
            var data = ExamineeService.GetByID(int.Parse(id));
            data.ViewCount += 1;
            ExamineeService.Save(data);
            return View(data);
        }
        [ValidateInput(false)]
        public ActionResult UpdateDescription(string content)
        {
            var examinee = ExamineeService.GetOneByLINQ(c=>c.UserID.Equals(Helper.SessionManagement.GetSessionReturnInt("UserID")));
            if(examinee==null)
                return Content("Fail");
            var data = ExamineeService.GetByID(examinee.ID);
            data.Description = content;

            var c1 = ExamineeService.Save(data);
            if (c1 > 0)
            {
                return Content("OK");
            }
            else
            {
                return Content("Fail");
            }
        }
    }
}

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Liên hệ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section HeadResource{
    <title>@ViewBag.Title</title>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&language=vn"></script>
    <link href="@Url.Content("~/Content/css/contact.css")" rel="stylesheet" type="text/css" />
}
@section BottomResource{
    <script src="@Url.Content("~/Content/js/contact.js")" type="text/javascript"></script>
}

<div class="main-content">
    <div class="grid-row">
        <div class="contact-view">
            <div class="module-head">
                <h4>
                    Thông tin liên hệ</h4>
            </div>
            <div class="contact-box">
                <h3>
                    Liên hệ với chúng tôi qua:</h3>
                <p>
                    456 Hai Bà Trưng, phường Tân Định, quận 1, TP.HCM</p>
                <p>
                    Số điện thoại: 016.5613.5162</p>
            </div>
            <div class="map-box">
                <div id="map-canvas">
                </div>
            </div>
            <div class="module-head">
                <h4>
                    Liên hệ</h4>
            </div>
            <div class="input-contact">
                @Html.Action("_AddContactComment", "CustomerIdea")
            </div>
        </div>
    </div>
</div>

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Home/ForgotPassword.cshtml
@{
    ViewBag.Title = "Phục hồi mật khẩu";
}
@section HeadResource{
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/css/loginpage.css")" rel="stylesheet" type="text/css" />
}
<div class="login-view">
    <div class="module-head">
        <h4>
            @ViewBag.Title</h4>
    </div>
    @using (Html.BeginForm("ForgotPassword", "Home", FormMethod.Post))
    { 
        <div class="std">
            @Html.ValidationSummary()
            <ul>
                <li>
                    <label>
                        Email để phục hồi mật khẩu:</label><input type="text" name="email" class="txt" />
                </li>
                <li>
                    <div class="control-register">
                        <input type="submit" class="button button-color-1" value="Chấp nhận" />
                    </div>
                </li>
            </ul>
        </div>
    }
</div>

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Home/Index.cshtml
@using CoreData
@{
    ViewBag.Title="Jbart Academy - cuộc thi ảnh";
    Layout = "~/Views/Shared/_Layout.cshtml";
   // List<Examinee> datat = new List<Examinee>();
  //  try{
       // var datat = (List<Examinee>)Session["dataindex"];
   // }catch{}
}
@section BannerIndex{
    <section id="primary">
        @Html.Action("_MainSlideShow", "BannerLogo")
    </section>
}

@*@section HeadResource{
      <script type="text/javascript" src="@Url.Content("~/Content/js/login.js")"></script>
}*@
<div class="container fluid">
    <div class="boxcontainer">

    @Html.Action("_ListExaminee", "Examinee")

    </div>

</div>

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Home/LoginHome.cshtml
@{
    ViewBag.Title = "Đăng nhập";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using CoreData
@model User
@section HeadResource{
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/css/login.css")" rel="stylesheet" type="text/css" />
}
@section BottomResource{
    <script src="@Url.Content("~/Content/js/login.js")" type="text/javascript"></script>
}
<div class="main-content">
    <div class="grid-row">
        @using (Html.BeginForm("LoginHome", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="login-view">
                <div class="intro-box">
                    <div class="box-inner">
                        <div class="content-login">
                            <div class="module-head">
                                <h4>
                                    Khách hàng mới</h4>
                            </div>
                            <div class="intro-to-register">
                                <p>
                                    Bạn là khách hàng mới và chưa có tài khoản tại Bello.vn? Vui lòng bỏ ra vài phút
                                    để đăng ký và trải nghiệm mua sắm online cùng Bello
                                </p>
                            </div>
                        </div>
                        <div class="control-register">
                            <a href="@Url.Action("Register", "Home")" class="btn btn-blue btn-register">Tạo tài khoản</a>
                        </div>
                    </div>
                </div>
                <div class="login-box">
                    <div class="box-inner">
                        <div class="content-login">
                            <div class="module-head">
                                <h4>
                                    Đã có tài khoản</h4>
                            </div>
                            @Html.ValidationSummary()
                            <ul>
                                <li>
                                    <label>
                                        Email</label>
                                    @Html.TextBoxFor(x => x.UserName, new { @class = "txt", @id = "UserName" })
                                </li>
                                <li>
                                    <label>
                                        Mật khẩu</label>
                                    @Html.PasswordFor(x => x.Password, new { @class = "txt", @id = "txt-Password" })
                                </li>
                                <li class="remember-acc">
                                    <label class="lbl-remember">
                                        Nhớ tài khoản</label>
                                    <input id="chk-remember" class="chk" type="checkbox" />
                                </li>
                                <li class="forgot-password"><a href="@Url.Action("ForgotPassword", "Home")">Quên mật khẩu ?</a></li>
                                <li class="control-register">
                                    <input id="btn-login" class="btn btn-login" type="submit" value="Đăng nhập" />
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Home/Register.cshtml
@{
    ViewBag.Title = "Đăng ký tài khoản mới";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using CoreData
@model User
@section HeadResource{
    <title>@ViewBag.Title</title>
}
<div class="login-view">
    <div class="login-box">
        <div class="box-inner">
            <div class="content-login">
                <div class="module-head">
                    <h4>
                        Tạo tài khoản mới</h4>
                </div>
                <div class="std">
                    @Html.ValidationSummary()
                    @using (Html.BeginForm("Register", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        <ul>
                            <li>
                                <label>
                                    Họ tên (*):</label>@Html.TextBoxFor(x => x.Name, new { @class = "txt" })</li>
                            <li>
                                <label>
                                    Tên đăng nhập (*):</label>@Html.TextBoxFor(x => x.UserName, new { @class = "txt" })</li>
                            <li>
                                <label>
                                    Mật khẩu (*):</label>@Html.PasswordFor(x => x.Password, new { @class = "txt", @id = "txt-Password" })</li>
                            <li>
                                <label>
                                    Nhập lại mật khẩu (*):</label>@Html.PasswordFor(x => x.TempPassWordExt, new { @class = "txt", @id = "txt-rePassword" })</li>
                            <li>
                                <label>
                                    Email:</label>@Html.TextBoxFor(x => x.Email, new { @class = "txt" })</li>
                            <li>
                                <label>
                                    Điện thoại (*):</label>@Html.TextBoxFor(x => x.Phone, new { @class = "txt" })</li>
                            <li>
                                <div class="inside-row">
                                    <label>
                                        Địa chỉ:</label>@Html.TextBoxFor(x => x.Address, new { @class = "txt" })</div>
                            </li>
                            <li class="control-register">
                                <input id="btn-register" class="button button-color-1" type="submit" value="Đăng ký tài khoản" />
                            </li>
                            
                           
                        </ul>
                    }
                </div>
                

                <div class="std">
                  
                   
                        <ul>
                           
                             <li class="control-register">
                                <form   action="@Url.Action("LoginFB", "Home")"
                        method="post">
                                <input id="btn1" class="button button-color-1" type="submit" value="Đăng ký bằng facebook" />
                                </form>
                            </li>
                           
                        </ul>
                   
                </div>



            </div>
        </div>
    </div>
</div>

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Home/_Header.cshtml
<header class="with-header-nav-menu">
    <div class="container clearfix">
        <div class="left-part">
            <nav class="menu-categories dropel">
                <a href="#" onclick="return false;" class="icon-menu-categories tooltip"
                    title="">Categories</a>
                @*<div class="dropdown">
                    <div class="dropdown-wrapper arrow-up-left">
                        <ul class="categories-list">
                            <li class="cat-item cat-item-13"><a href="#"
                                title="شاهد جميع المقالات في تصنيف Celebrities">Make up</a> </li>
                            <li class="cat-item cat-item-1"><a href="#"
                                title="شاهد جميع المقالات في تصنيف Commercial">Hair</a> </li>
                            <li class="cat-item cat-item-14"><a href="#"
                                title="شاهد جميع المقالات في تصنيف Landscapes">Esthetics</a> </li>
                            <li class="cat-item cat-item-19"><a href="#"
                                title="شاهد جميع المقالات في تصنيف Sport">Nails</a> </li>
                        </ul>
                    </div>
                </div>*@
            </nav>
            <div class="search-box clearfix dropel">
                <a href="#" onclick="return false;" class="icon-zoom">
                    Search</a>
                <div class="dropdown">
                    <div class="dropdown-wrapper arrow-up-left">
                        @Html.Action("_SearchInputControl", "Search")
                    </div>
                </div>
            </div>
        </div>
        <h1 class="logo">
            <a href="@Url.Action("Index", "Home")" title="Jbart - cuộc thi ảnh">
                <img src="/Media/Jbart/@ViewBag.Logo"  alt="Jbart - cuộc thi ảnh">
            </a>
        </h1>
        <div class="right-part">
            <div class="log-in-out dropel">
                @if (Session["UserID"] == null || Session["UserID"].ToString() == "")
                {
                <a href="#" onclick="return false;" title="ĐĂNG ẢNH" class="icon-login tooltip">ĐĂNG ẢNH</a>
                <div class="dropdown">
                    <div class="dropdown-wrapper arrow-up-right">
                        <div id="login-form">
                            @*<form name="login-form" id="login-form" action="@Url.Action("LoginHome","Home")"
                        method="post">*@
                            <p class="login-username">
                                <label for="user_login">
                                    Tài khoản</label>
                                <input type="text" name="log" id="user_login" class="input" value="Tài khoản" size="20">
                            </p>
                            <p class="login-password">
                                <label for="user_pass">
                                    Mật khẩu</label>
                                <input type="password" name="pwd" id="user_pass" class="input" value="password" size="20">
                            </p>
                            <p class="login-submit">
                                <input type="submit" name="wp-submit" id="wp-submit" class="button-primary loginweb" value="Login">
                                       
                                  
                            </p>
                              <p class="login-submit">
                            <form style="text-align: left;"  action="@Url.Action("LoginFB", "Home")"
                        method="post">
                                <input type="submit" name="wp-submit" id="wp-submit" class="button-primary loginFBweb" value="Login with facebook">
                                       
                                  </form>
                            </p>
                            @*</form>*@
                        </div>
                        <p class="login-links clearfix">
                            <span class="fleft"><a href="@Url.Action("ForgotPassword", "Home")"
                                title="Lost password">Quên mật khẩu ?</a> </span><span class="fright"><a href="@Url.Action("Register", "Home")">
                                    Đăng ký</a></span>
                        </p>
                    </div>
                </div>
                }
                else
                {
                    <a href="#" title="Đã đăng Nhập" class="tooltip">Xin chào, @Session["UserName"]</a>
                    <div class="dropdown">
                    <div class="dropdown-wrapper arrow-up-right">
                        <div id="login-form" style="width:150px">
                           <p class="login-username">
                                <a href="@Url.Action("Profile", "User")">Thông tin cá nhân</a>
                            </p>
                            <p class="login-username">
                                <a href="@Url.Action("LogOffHome", "Home")">Thoát</a>
                            </p>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
    <div class="container fluid clearfix">
        <a href="http://pinthis-rtl.pixelbeautify.com/#" onclick="return false;" class="icon-nav-menu">
            Menu</a>
        <div class="header-menu">
            <div class="header-menu-wrapper arrow-up-right">
                <ul id="menu-menu-1" class="header-menu-list">
                    <li id="menu-item-241" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-241">
                        <a href="/">Trang chủ</a>
                       
                    </li>
                    @Html.Action("_GetArticleDefault", "Article")
                   @* <li id="menu-item-231" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-231">
                        <a href="@Url.Action("Detail", "Article", new { @id = "" + 12 + "", name = @Helper.StringHelper.RemoveVietNamString(Model.Title)})">Giới thiệu</a></li>
                    <li id="menu-item-232" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-232">
                         <a href="@Url.Action("Detail", "Article", new { @id = "" + 13 + "", name = @Helper.StringHelper.RemoveVietNamString(Model.Title)})">Thể lệ cuộc thi</a></li>
                   <li id="menu-item-232" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-232">
                         <a href="@Url.Action("Detail", "Article", new { @id = "" + 15 + "", name = @Helper.StringHelper.RemoveVietNamString(Model.Title)})">Nội dung thi</a></li>
                    <li id="menu-item-244" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-244">
                         <a href="@Url.Action("Detail", "Article", new { @id = "" + 14 + "", name = @Helper.StringHelper.RemoveVietNamString(Model.Title)})">Giải thưởng</a></li>*@
                   
                </ul>
            </div>
        </div>
    </div>
</header>

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Home/_LoginFacebookButton.cshtml
  <p class="login-submit">
                            <form style="text-align: left;"  action="@Url.Action("LoginFB", "Home")"
                        method="post">
                                <input type="submit" name="wp-submit" id="wp-submit" class="button-primary loginFBweb" value="Login with facebook">
                                       
                                  </form>
                            </p>

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Home/_TopInforContact.cshtml
<div class="nav-contact">
    <div class="main-contact">
        <a href="#" class="lu-icon nav-contact-icon"></a><span>Hot Line</span> <span class="phone-number">
            016.5613.5162</span>
        <div class="clearfix">
        </div>
    </div>
    <div class="contact-infor">
        <ul>
            <li><span class="lu-icon lu-phone-icon"></span><span>016.5613.5162</span> </li>
            <li><span class="lu-icon lu-skype-icon"></span><span><a href="#">Nhân viên 1</a></span>
            </li>
        </ul>
    </div>
</div>

cuocthianh/Source/webportalcuocthianh/CameraShop/Views/Home/_TopMenu.cshtml
<div class="navbar-top">
    <ul>
        <li><a href="#">Chính sách</a></li>
        <li><a href="#">Hướng dẫn</a></li>
        <li><a href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
        <li><a href="#">Thông tin</a></li>
    </ul>
</div>